var arr = [5, 10, 10, 6, 5]
var nilaiUnik = []
var jumlahMuncul = []
var index = 0
var counter = 1
console.log('saat i = 0')
console.log('cek limit i<arr.length => 0 < 5. terpenuhi, jalankan loop')
console.log('lakukan looping')
console.log('   saat j = 0')
console.log('cek limit j<nilaiUnik.length => 0 < 0. tidak terpenuhi, tidak jalankan loop')
console.log('karena isSame = false, lakukan else')
nilaiUnik.push(arr[0])
jumlahMuncul[0] = 1
console.log('nilaiUnik saat ini = ' , nilaiUnik)
console.log('jumlahMuncul saat ini = ' , jumlahMuncul)
console.log('==========================================================')
console.log('saat i = 1')
console.log('cek limit i<arr.length => 1 < 5. terpenuhi, jalankan loop')
console.log('lakukan looping')
console.log('   saat j = 0')
console.log('cek limit j<nilaiUnik.length => 0 < 1. terpenuhi, jalankan loop')
console.log('   if tidak berjalan karena arr[1] !== nilaiUnik[0] (10) ! == (5)')
console.log('   saat j = 1')
console.log('cek limit j<nilaiUnik.length => 1 < 1. tidak terpenuhi, keluar loop')
console.log('karena isSame = false, lakukan else')
nilaiUnik.push(arr[1])
jumlahMuncul[1] = 1
console.log('nilaiUnik saat ini = ' , nilaiUnik)
console.log('jumlahMuncul saat ini = ' , jumlahMuncul)
console.log('==========================================================')
console.log('saat i = 2')
console.log('cek limit i<arr.length => 2 < 5. terpenuhi, jalankan loop')
console.log('lakukan looping')
console.log('   saat j = 0')
console.log('cek limit j<nilaiUnik.length => 0 < 2. terpenuhi, jalankan loop')
console.log('   if tidak berjalan karena arr[2] !== nilaiUnik[0] (10) ! == (5)')
console.log('   saat j = 1')
console.log('cek limit j<nilaiUnik.length => 1 < 2. terpenuhi, jalankan loop')
console.log('   if  berjalan karena arr[2] === nilaiUnik[1] (10) === (10)')
console.log('lakukan if')
isSame = true
index = 1
console.log('saat j = 2')
console.log('cek limit j<nilaiUnik.length => 2 < 2. tidak terpenuhi, keluar loop')
console.log('karena isSame = true, lakukan if')
counter = counter + 1
jumlahMuncul[index] = counter
console.log('nilaiUnik saat ini = ' , nilaiUnik)
console.log('jumlahMuncul saat ini = ' , jumlahMuncul)
console.log('==========================================================')
console.log('saat i = 3')
console.log('cek limit i<arr.length => 3 < 5. terpenuhi, jalankan loop')
console.log('lakukan looping')
console.log('   saat j = 0')
console.log('cek limit j<nilaiUnik.length => 0 < 3. terpenuhi, jalankan loop')
console.log('   if tidak berjalan karena arr[3] !== nilaiUnik[0] (6) ! == (5)')
console.log('   saat j = 1')
console.log('cek limit j<nilaiUnik.length => 1 < 3. terpenuhi, jalankan loop')
console.log('   if  tidak berjalan karena arr[3] !== nilaiUnik[1] (6) === (10)')
console.log('   saat j = 2')
console.log('cek limit j<nilaiUnik.length => 2 < 3. terpenuhi, jalankan loop')
console.log('   if tidak berjalan karena arr[3] !== nilaiUnik[2] (6) === (10)')
console.log('   saat j = 3')
console.log('cek limit j<nilaiUnik.length => 3 < 3. tidak terpenuhi, keluar loop')
console.log('karena isSame = false, lakukan else')
nilaiUnik.push(arr[3])
jumlahMuncul[3] = 1
console.log('nilaiUnik saat ini = ' , nilaiUnik)
console.log('jumlahMuncul saat ini = ' , jumlahMuncul)
console.log('==========================================================')
console.log('saat i = 4')
console.log('cek limit i<arr.length => 4 < 5. terpenuhi, jalankan loop')
console.log('lakukan looping')
console.log('   saat j = 0')
console.log('cek limit j<nilaiUnik.length => 0 < 4. terpenuhi, jalankan loop')
console.log('   if berjalan karena arr[4] === nilaiUnik[0] (5) === (5)')
console.log('lakukan if')
isSame = true
index = 0 // nilai j = 0
console.log('   saat j = 1')
console.log('cek limit j<nilaiUnik.length => 1 < 4. terpenuhi, jalankan loop')
console.log('   if  tidak berjalan karena arr[4] !== nilaiUnik[1] (5) === (10)')
console.log('   saat j = 2')
console.log('cek limit j<nilaiUnik.length => 2 < 4. terpenuhi, jalankan loop')
console.log('   if tidak berjalan karena arr[4] !== nilaiUnik[2] (5) === (10)')
console.log('   saat j = 3')
console.log('cek limit j<nilaiUnik.length => 3 < 4. terpenuhi, jalankan loop')
console.log('   if tidak berjalan karena arr[4] !== nilaiUnik[3] (5) === (6)')
console.log ('  saat j = 4, cek limit 4 < 4 tidak terpenuhi keluar loop')
console.log('karena issame = true, jalankan if')
counter = counter + 1
jumlahMuncul[0] = counter
console.log('nilaiUnik saat ini = ' , nilaiUnik)
console.log('jumlahMuncul saat ini = ' , jumlahMuncul)

